"""
Generate the frontend's citation matcher from `core/ids.py`.

The backend decides which citations are VERIFIED; the frontend decides which
are CLICKABLE. Both must recognise the same shapes, and a shape only one side
knows about produces a verified citation with nothing in the prose pointing at
it — a bug with no error message.

The previous system wrote the regex twice and kept the two in step with a
parity test. That test caught real drift (a UI that knew `§8(5)` but not
`rule 6(1)`, so every Rules citation rendered unlinkable), but a test that
detects divergence is a workaround. Not diverging is the design.

    python scripts/build_frontend_spec.py

Writes frontend/assets/citations.js. Commit the output — the frontend deploys
as static files with no build step, so anything not checked in is not there.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core import ids                                        # noqa: E402

# The frontend is a SIBLING of the backend, not a subfolder of it. Written
# with one `.parent` too few, this silently created `backend/frontend/assets/`
# and wrote there — the script reported success, and the real page kept the
# stale matcher it already had. Overridable so a different layout does not
# need a code edit.
OUT = Path(os.environ.get("DPDP_FRONTEND_DIR")
           or Path(__file__).resolve().parent.parent.parent / "frontend"
           ) / "assets" / "citations.js"

TEMPLATE = '''// GENERATED by scripts/build_frontend_spec.py — do not edit.
//
// Compiled from core/ids.py so the two sides cannot drift. The backend
// decides which citations are verified; this decides which are clickable, and
// a shape only one side knows makes a verified citation unlinkable with no
// error anywhere.
//
// Matching is on NODE IDS, never printed labels: "section 8(5)", "\\u00a78(5)"
// and "\\u00a7 8 (5)" are three spellings of s-8-5, so comparing label strings
// lights up only whichever spelling the backend happened to print.

export const CITATION = new RegExp(%(pattern)s, "gi");
const PART = new RegExp(%(part)s, "g");

/** The provision id a matched citation points at, or null. */
export function nodeIdFor(groups) {
  const parts = (s) => [...(s || "").matchAll(PART)].map((m) => m[1]);
  if (groups.sec)   return ["s", groups.sec, ...parts(groups.sec_parts)].join("-");
  if (groups.rule)  return ["r", groups.rule, ...parts(groups.rule_parts)].join("-");
  if (groups.entry) return `pen-${groups.entry}`;
  if (groups.ord) {
    const base = `rules-sch-${groups.ord.toLowerCase()}`;
    return groups.part ? `${base}-part-${groups.part.toLowerCase()}` : base;
  }
  return null;
}

/** Every citation in `text`, de-duplicated, in order. */
export function findCitations(text) {
  const seen = new Set();
  const out = [];
  CITATION.lastIndex = 0;
  for (const m of text.matchAll(CITATION)) {
    const id = nodeIdFor(m.groups || {});
    if (id && !seen.has(id)) { seen.add(id); out.push({ id, match: m[0] }); }
  }
  return out;
}
'''


def main() -> None:
    spec = ids.spec()
    # Python's named groups are (?P<x>…); JavaScript's are (?<x>…).
    pattern = spec.pattern.replace("(?P<", "(?<")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        TEMPLATE % {"pattern": _js_string(pattern),
                    "part": _js_string(spec.part_pattern)},
        encoding="utf-8")

    # Prove the generated grammar still resolves every shape the backend
    # produces. Generating a broken matcher silently would reintroduce exactly
    # the bug this script exists to prevent.
    cases = {
        "section 8(5)": "s-8-5", "§8(5)": "s-8-5", "§ 8 (5)": "s-8-5",
        "Section 8": "s-8", "rule 6(1)": "r-6-1", "rules 6": "r-6",
        "Schedule entry 2": "pen-2", "Schedule 2": "pen-2",
        "First Schedule": "rules-sch-first",
        "Part B of First Schedule": "rules-sch-first-part-b",
        "Third Schedule": "rules-sch-third",
    }
    bad = []
    for text, want in cases.items():
        match = ids.CITATION.search(text)
        got = ids.node_id_from_match(match) if match else None
        if got != want:
            bad.append((text, got, want))
    if bad:
        raise SystemExit(f"citation grammar is broken: {bad}")

    print(f"wrote {OUT.relative_to(OUT.parent.parent.parent)}  "
          f"({len(cases)} shapes verified)")


def _js_string(pattern: str) -> str:
    return '"' + pattern.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
